# Generated by Django 3.2.23 on 2026-02-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='descripcion'),
        ),
    ]
